In [8]:
import pandas as pd

# Load the datasets into pandas DataFrames
rides_df = pd.read_csv(r"C:\Users\Avinash rai\Downloads\data\rides_dataset1.csv")
payment_df = pd.read_csv(r"C:\Users\Avinash rai\Downloads\data\payment_dataset4.csv")
driver_df = pd.read_csv(r"C:\Users\Avinash rai\Downloads\data\driver_dataset3.csv")
city_df = pd.read_csv(r"C:\Users\Avinash rai\Downloads\data\city_dataset2.csv")

# Display the first few rows of each dataframe to inspect the data
print(rides_df.head())
print(payment_df.head())
print(driver_df.head())
print(city_df.head())

                                ride_id          start_city          end_city  \
0  b26d2384-e990-4269-a1b7-6c6e433cfc1d  North Colleenville      Douglasmouth
1  3ef0d969-d19c-4ec1-abed-4fa986168c90            Cindyton  West Melanieland
2  e975dbb0-b118-4431-8228-769b554513d0            Maryberg   New Rachelville
3  c709e75a-9974-4857-8445-d5f9a878f26b  South Cameronmouth       South Shawn
4  c811ae95-ea1f-4859-9df4-0307f484d988          Howardside         New Ricky

    ride_date start_time  end_time  distance_km        fare dynamic_pricing  \
0  2024-04-30   06:57:05  23:06:53     2.895034  142.100117              No
1  2022-11-10   14:22:49  02:08:02    28.864365  175.960761              No
2  2021-06-11   12:17:53  01:24:20    21.807327  119.509820             Yes
3  2022-09-05   08:48:50  12:29:13    17.868135  120.173518             Yes
4  2024-06-21   17:59:12  16:05:55     7.483889  175.566156              No

                              driver_id                          passenger_id  \
0  dfe2f726-7760-4fa1-8688-2120938d4c2e  922ec7c2-bcf2-4756-ba85-0fd55739dc2a
1  72c4a06e-24d1-4221-8352-3842577f5ad9  7d65fef1-8ac1-458b-be1b-5fbe2b5c4f9a
2  23c554c6-a183-4b59-8e0b-9c5ba699e98c  a4e4cfcd-14b6-444c-9a38-0bc3d65d74ce
3  dcb0d8bf-a327-4f54-8678-8f0d48335812  a902951a-9950-48f5-8f4b-c3e8df004850
4  3faf2901-ab93-471b-883b-17520d3bcc06  d8a535e3-b7e7-4005-9d81-353f57c24cfb

   rating payment_method ride_status
0       2           Cash   Completed
1       1           Cash    Canceled
2       1         PayPal   Completed
3       4         PayPal    Canceled
4       2    Credit Card    Canceled
                             payment_id                               ride_id  \
0  cac819cd-71c2-4c58-8547-20e1b20d18b4  49edba3e-f4d5-45af-a86b-85d4dacd06b9
1  65490c09-6871-43b1-9f50-4fd27d31f5c4  8c3cb279-b637-4ec6-b7a4-5529adccf4c6
2  7f00a3c1-5f6b-4d6b-9d26-3d7c4448d659  52796e17-4e2a-42ef-901f-9245bf52a9f5
3  198fd6a6-f121-4f52-9c70-f6eac79f70d5  4d9d2189-48fc-407d-a34f-ed86aec7f428
4  36a7a569-2231-486d-8f90-0a1eb27e09b5  f44113c2-9777-4d2e-b9f0-8e2c0136e331

                              driver_id                          passenger_id  \
0  4cf72587-4f42-41af-9950-851a770818f6  3d774faa-e663-44fd-96a6-b7a991928189
1  a324a87d-62f4-42ef-af66-f819c19ed9cf  fb087c05-2184-4f38-b47c-ee71ce43986e
2  14dfc25f-12c8-4404-9c28-30b54d542cb0  f903b81a-41c3-437f-96d8-85097f599bfd
3  d841fa68-826d-42dc-ab1b-b0532cbf54cf  174b2d35-c4ef-40f7-bf70-30c61810d63e
4  7c372422-4915-4e5f-8acf-c8aaba2cc866  c3acfb28-202b-4747-9922-b187893aa86c

         fare  surge_multiplier payment_method  driver_earnings  \
0  104.211158          1.586988           Cash       543.998701
1  113.664531          2.418041    Credit Card       585.806665
2   11.884105          1.136048           Cash       465.747529
3   70.614096          1.099451    Credit Card       603.422543
4         NaN          1.111742    Credit Card       692.648169

   uber_commission transaction_status payment_date
0        38.125827             Failed   2021-03-05
1        28.005699             Failed   2020-04-19
2         5.676429            Pending   2021-04-07
3        39.750477            Pending   2022-06-14
4        10.530703            Pending   2022-09-17
                              driver_id          driver_name  age  gender  \
0  7f69a8b5-dac4-41b4-8151-d3b43dca077b           Jack Smith   31    Male
1  5a8095f0-c17b-4ef5-af99-0dfb12be50ba       Bryan Gonzalez   63  Female
2  9a8656e0-8732-4018-9acd-6f414e4c145f  Katelyn Fitzpatrick   64    Male
3  395890e1-c72a-4d08-ad6d-fe67878a66e9       Parker Gilbert   59    Male
4  4712d10b-aacb-463c-84ac-2f7b11e35a5f         Joseph Scott   43  Female

                                city_id vehicle_type  avg_driver_rating  \
0  b25b9b1f-1dd8-4f94-bf9c-e31894fb1179          Car           4.963069
1  4709dea2-b2ac-45cb-9d8c-817511ada331          Car           1.261725
2  1aee75b9-ec7a-4d10-bdf5-e91ba5ce3559          Van           1.912878
3  07b3d26b-8c4f-4148-9a41-00c66813244c          Car           2.052264
4  6f049b7e-5ff6-4c42-af33-c700ffdafc6b          Car           6.391593

   total_rides  total_earnings driver_status employment_type  \
0         4969     7138.716234      Inactive       Full-time
1         4583    12459.853889     Suspended       Full-time
2         4196     3960.993945     Suspended       Full-time
3           58    32063.924198     Suspended       Full-time
4         4665    34616.093513      Inactive       Full-time

   years_of_experience  ride_acceptance_rate
0                    7             91.851612
1                    3             81.808887
2                   10             79.265997
3                   13             97.649575
4                   16             51.009616
                                city_id         city_name           country  \
0  9d978b1c-6617-4cf6-95c4-95dc9a248d70       Port Joseph           Senegal
1  b7408700-0d17-4705-920d-26a080d0e4a5  Port Shannonside            France
2  3aecee16-ccd8-4805-881a-19e1095cccd7   Lake Donnaville  Marshall Islands
3  0a07d46b-02fd-4a58-90b5-94b4ce68e2f9     North Phyllis           Burundi
4  c6c6994a-4bab-41fe-a2eb-66908cedb34e      Lake Patrick     Liechtenstein

       continent  population regulatory_status market_competition  \
0  South America   4981867.0        Restricted             Medium
1         Europe   4901993.0            Banned                Low
2  South America   2177603.0        Restricted                Low
3  North America         NaN           Allowed               High
4  South America         NaN        Restricted             Medium

   number_of_drivers  number_of_rides    avg_fare  avg_wait_time_min  \
0              15141            84106   27.507420           3.707850
1              23664           209575   64.408369          17.344458
2               9516            19003  195.306864           6.577905
3              18143           228002   56.610778          13.280884
4               8401            26567   11.111732          19.038678

  uber_services major_competitors
0         UberX              Grab
1         UberX       Local Taxis
2      UberPool              Lyft
3         UberX       Local Taxis
4         UberX       Local Taxis

In [11]:
# Check data types and missing values
print(rides_df.info())   # Show data types and non-null counts
print(payment_df.info())
print(driver_df.info())
print(city_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ride_id          475 non-null    object
 1   start_city       500 non-null    object
 2   end_city         500 non-null    object
 3   ride_date        500 non-null    object
 4   start_time       500 non-null    object
 5   end_time         500 non-null    object
 6   distance_km      500 non-null    float64
 7   fare             447 non-null    float64
 8   dynamic_pricing  500 non-null    object
 9   driver_id        500 non-null    object
 10  passenger_id     500 non-null    object
 11  rating           500 non-null    int64
 12  payment_method   500 non-null    object
 13  ride_status      500 non-null    object
dtypes: float64(2), int64(1), object(11)
memory usage: 54.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   payment_id          500 non-null    object
 1   ride_id             500 non-null    object
 2   driver_id           500 non-null    object
 3   passenger_id        500 non-null    object
 4   fare                446 non-null    float64
 5   surge_multiplier    500 non-null    float64
 6   payment_method      500 non-null    object
 7   driver_earnings     500 non-null    float64
 8   uber_commission     500 non-null    float64
 9   transaction_status  500 non-null    object
 10  payment_date        500 non-null    object
dtypes: float64(4), object(7)
memory usage: 43.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   driver_id             473 non-null    object
 1   driver_name           500 non-null    object
 2   age                   500 non-null    int64
 3   gender                500 non-null    object
 4   city_id               500 non-null    object
 5   vehicle_type          500 non-null    object
 6   avg_driver_rating     500 non-null    float64
 7   total_rides           500 non-null    int64
 8   total_earnings        500 non-null    float64
 9   driver_status         500 non-null    object
 10  employment_type       500 non-null    object
 11  years_of_experience   500 non-null    int64
 12  ride_acceptance_rate  500 non-null    float64
dtypes: float64(3), int64(3), object(7)
memory usage: 50.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   city_id             500 non-null    object
 1   city_name           500 non-null    object
 2   country             500 non-null    object
 3   continent           500 non-null    object
 4   population          447 non-null    float64
 5   regulatory_status   500 non-null    object
 6   market_competition  500 non-null    object
 7   number_of_drivers   500 non-null    int64
 8   number_of_rides     500 non-null    int64
 9   avg_fare            500 non-null    float64
 10  avg_wait_time_min   500 non-null    float64
 11  uber_services       500 non-null    object
 12  major_competitors   500 non-null    object
dtypes: float64(3), int64(2), object(8)
memory usage: 50.9+ KB
None

In [12]:
# Check for missing values
print(rides_df.isnull().sum())
print(payment_df.isnull().sum())
print(driver_df.isnull().sum())
print(city_df.isnull().sum())

ride_id            25
start_city          0
end_city            0
ride_date           0
start_time          0
end_time            0
distance_km         0
fare               53
dynamic_pricing     0
driver_id           0
passenger_id        0
rating              0
payment_method      0
ride_status         0
dtype: int64
payment_id             0
ride_id                0
driver_id              0
passenger_id           0
fare                  54
surge_multiplier       0
payment_method         0
driver_earnings        0
uber_commission        0
transaction_status     0
payment_date           0
dtype: int64
driver_id               27
driver_name              0
age                      0
gender                   0
city_id                  0
vehicle_type             0
avg_driver_rating        0
total_rides              0
total_earnings           0
driver_status            0
employment_type          0
years_of_experience      0
ride_acceptance_rate     0
dtype: int64
city_id                0
city_name              0
country                0
continent              0
population            53
regulatory_status      0
market_competition     0
number_of_drivers      0
number_of_rides        0
avg_fare               0
avg_wait_time_min      0
uber_services          0
major_competitors      0
dtype: int64

1. Cleaning the Rides Dataset (rides_df)
We need to handle missing values in the ride_id and fare columns.

Missing ride_id: Since ride_id is a key identifier, rows with missing ride_id should be dropped.
Missing fare: Missing fare values can be filled with the median value from the fare column.

In [13]:
# Remove rows where 'ride_id' is missing (essential for identification)
rides_df.dropna(subset=['ride_id'], inplace=True)

# Fill missing 'fare' with the median value
rides_df['fare'].fillna(rides_df['fare'].median(), inplace=True)

# After cleaning, remove duplicate rows
rides_df.drop_duplicates(inplace=True)

2. Cleaning the Payment Dataset (payment_df)
Missing fare: Similar to the rides_df, fill missing fare values with the median of the column

In [14]:
# Fill missing 'fare' in payment data with the median value
payment_df['fare'].fillna(payment_df['fare'].median(), inplace=True)

# Remove duplicate rows
payment_df.drop_duplicates(inplace=True)

## 3. Cleaning the Driver Dataset (driver_df)
Missing driver_id: If driver_id is missing, the row should be dropped since it’s essential.
Other Columns: For columns like age or avg_driver_rating, fill missing values with the median or mean.

In [15]:
# Remove rows with missing 'driver_id' (essential identifier)
driver_df.dropna(subset=['driver_id'], inplace=True)

# Fill missing 'age' with the median value
driver_df['age'].fillna(driver_df['age'].median(), inplace=True)

# Fill missing 'avg_driver_rating' with the mean value
driver_df['avg_driver_rating'].fillna(driver_df['avg_driver_rating'].mean(), inplace=True)

# Remove duplicates
driver_df.drop_duplicates(inplace=True)

## 4. Cleaning the City Dataset (city_df)
Missing population: We can fill missing values in the population column with the median value.
Other Columns: No missing values need to be handled, but we’ll remove duplicates.

In [16]:
# Fill missing 'population' with the median value
city_df['population'].fillna(city_df['population'].median(), inplace=True)

# Remove duplicates
city_df.drop_duplicates(inplace=True)

## 5. Save Cleaned Data
After cleaning the datasets, save the cleaned dataframes back into new CSV files:

In [17]:
# Save the cleaned data to new CSV files
rides_df.to_csv(r"D:\Uber-Operational-Data-Analysis\cleaned_data\rides_dataset_cleaned.csv", index=False)
payment_df.to_csv(r"D:\Uber-Operational-Data-Analysis\cleaned_data\payment_dataset_cleaned.csv", index=False)
driver_df.to_csv(r"D:\Uber-Operational-Data-Analysis\cleaned_data\driver_dataset_cleaned.csv", index=False)
city_df.to_csv(r"D:\Uber-Operational-Data-Analysis\cleaned_data\city_dataset_cleaned.csv", index=False)

6. Re-check the Cleaned Data
Finally, re-check the cleaned data to ensure there are no missing values left.

In [19]:
# Inspect cleaned data to confirm that no missing values remain
print(rides_df.isnull().sum())
print(payment_df.isnull().sum())
print(driver_df.isnull().sum())
print(city_df.isnull().sum())

ride_id            0
start_city         0
end_city           0
ride_date          0
start_time         0
end_time           0
distance_km        0
fare               0
dynamic_pricing    0
driver_id          0
passenger_id       0
rating             0
payment_method     0
ride_status        0
dtype: int64
payment_id            0
ride_id               0
driver_id             0
passenger_id          0
fare                  0
surge_multiplier      0
payment_method        0
driver_earnings       0
uber_commission       0
transaction_status    0
payment_date          0
dtype: int64
driver_id               0
driver_name             0
age                     0
gender                  0
city_id                 0
vehicle_type            0
avg_driver_rating       0
total_rides             0
total_earnings          0
driver_status           0
employment_type         0
years_of_experience     0
ride_acceptance_rate    0
dtype: int64
city_id               0
city_name             0
country               0
continent             0
population            0
regulatory_status     0
market_competition    0
number_of_drivers     0
number_of_rides       0
avg_fare              0
avg_wait_time_min     0
uber_services         0
major_competitors     0
dtype: int64